# Generated by Django 6.0.5 on 2026-06-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologoprofile',
            name='tarjeta_profesional',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
